config/routes.rb
require 'api_constraints'

Spacer::Application.routes.draw do
  devise_for :runners

  root 'races#index'

  resources :races do
    resources :runners
  end

  resources :messages, only: [:index, :show]

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resource :message, only: [:create]
      resources :messages do
        post "approve"
        post "reject"
      end
      resources :races do
        resource :participations, only: [:create]
        member do
          get 'levels'
        end
      end
    end
  end

  

end

app/views/layouts/_messages.html.erb
<div class="row" style="margin-top: 60px">
	<% if notice.is_a?(String) && !notice.empty? %>
	<p class="notice"><%= notice %></p>
	<% end %>
	<% if alert.is_a?(String) && !alert.empty? %>
	<p class="alert"><%= alert %></p>
	<% end %>
</div>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "#{name}" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
  <title>Ultra Pacers</title>
  <meta name="description" content="Find and nominate yourself as pacer in ultra running races">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ultra Pacers</a>
        <div class="nav-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
          </ul>
          <div class="nav navbar-nav pull-right navbar-text">
          <% if runner_signed_in? %>
            <a href="/messages" class="btn btn-danger btn-xs"><%= current_runner.messages.unread(current_runner).count %></a>
          	<a href="<%= edit_runner_registration_path %>"><span class="navbar-text" style="color: white"><%= current_runner.username %> </span></a>
          	<%= link_to('Logout', destroy_runner_session_path, :method => :delete) %>
         	<% else %>
          	<%= form_for("runner", :url => runner_session_path, html: { class: "form-inline pull-left" }) do |f| %>
  						<%= f.text_field :email, placeholder: "email" %>
  						<%= f.password_field :password, placeholder: "passwoed" %>
  						<%= f.submit 'Sign In' %>
						<% end %>
              <%= link_to('Sign Up', new_runner_registration_path, {class: "pull-right", style: "margin-left: 10px"}) %>
          <% end %>
        	</div>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    <div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
		</div>
<script data-turbolinks-eval=false>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42995635-1', 'ultrapacers.org');
  ga('send', 'pageview');

</script>
<!-- UserVoice JavaScript SDK (only needed once on a page) -->
<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/m34xUtCODjboZPY7vJ2fVw.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

<!-- A tab to launch the Classic Widget -->
<script  data-turbolinks-eval=false>
UserVoice = window.UserVoice || [];
UserVoice.push(['showTab', 'classic_widget', {
  mode: 'full',
  primary_color: '#cc6d00',
  link_color: '#007dbf',
  default_mode: 'support',
  forum_id: 218095,
  tab_label: 'Feedback & Support',
  tab_color: '#cc6d00',
  tab_position: 'middle-right',
  tab_inverted: false
}]);
</script>
</body>
</html>